repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: bash -c 'cd server && poetry run black --check app'
    language: python
  - id: flake8
    name: flake8
    entry: bash -c 'cd server && poetry run flake8 app'
    language: python
  - id: mypy
    name: mypy
    entry: bash -c 'cd server && poetry run mypy app'
    language: python
  - id: eslint
    name: eslint
    entry: bash -c 'cd gui && npm run eslint'
    language: node
  - id: prettier
    name: prettier
    entry: bash -c 'cd gui && npm run prettier:check'
    language: node
