name: thesis
services:
  server:
    container_name: server
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - 8086:8086
  gui:
    container_name: gui
    build:
      context: ./gui
    env_file:
      - ./gui/.env
    ports:
      - 3000:3000
