name: thesis
services:
  server:
    container_name: thesis_server
    networks:
      - thesis
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - 8086:8086
  gui:
    container_name: thesis_gui
    networks:
      - thesis
    build:
      context: ./gui
    env_file:
      - ./gui/.env
    ports:
      - 3000:3000
  redis:
    container_name: thesis_redis
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - thesis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
      - 8001:8001
  db:
    container_name: thesis_db
    image: postgres:15-bookworm
    restart: unless-stopped
    networks:
      - thesis
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: thesis
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    command: ["postgres"]
#    command: ["postgres", "-c", "log_statement=all", "-c", "log_duration=on", "-c", "log_destination=csvlog", "-c", "logging_collector=on"]

networks:
  thesis:
    driver: bridge