[tool.poetry]
name = "thesis"
version = "0.1.0"
description = ""
authors = ["Matěj Ščerba <m.scerba@seznam.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
