export enum Event {
  ALTERNATIVE_ADDED_TO_CANDIDATES = "ALTERNATIVE_ADDED_TO_CANDIDATES",
  ALTERNATIVE_DISCARDED = "ALTERNATIVE_DISCARDED",
  FILTERED_PRODUCT_ADDED_TO_CANDIDATES = "FILTERED_PRODUCT_ADDED_TO_CANDIDATES",
  FILTERED_PRODUCT_DISCARDED = "FILTERED_PRODUCT_DISCARDED",
  DISCARDED_ADDED_TO_CANDIDATES = "DISCARDED_ADDED_TO_CANDIDATES",
  CANDIDATE_DISCARDED = "CANDIDATE_DISCARDED",
  QUESTIONNAIRE_SUBMITTED = "QUESTIONNAIRE_SUBMITTED",
}
